### PR TITLE
Fix sensuctl install and configure for Windows

### PR DESCRIPTION
**Pull request by kovukono**
#Pull Request Checklist

**Is this in reference to an existing issue?**
No

#### General

- [X] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [X] Update README with any necessary configuration snippets

- [ ] Cookstyle (rubocop) passes

- [x] Foodcritic passes

- [x] Rspec (unit tests) passes

- [x] Inspec (integration tests) passes

#### New Features

- [ ] Added a [Testing Artifact](https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts) as either an automated test or a manual artifact on the PR.

- [ ] Added documentation for it to the `README.md`

#### Purpose
sensuctl's first file extract on Windows was being extracted to a different file than was referenced in the second extract.

Windows was downloading the file for sensuctl installation every time without checking to see if it was currently installed.

Windows was having issues with parsing the array of arguments for configuring sensuctl.

### CODE REVIEW

**Comment by webframp** [comment]
@kovukono Have you looked at #112 ? It refactors the download process on windows, would you be able to provide some feedback there as well?

**Comment by kovukono** [comment]
@webframp Unfortunately no. We're using Chef 14, and having to fork the repo to make it work. I can't verify a Chef 15 feature.

**Comment by webframp** [comment]
@kovukono cookstyle failure in travis shows that this branch doesn't include the fix from #108, could you rebase off of master and update this branch? 

I expect that will fix the issue with ci

**Comment by kovukono** [comment]
@webframp Pulled it in, hopefully it fixes it, but Travis is really slow today. Thanks for the heads up.

**Comment by webframp** [comment]
> Travis is really slow today.

It's been painfully slow all day! 

Thanks for the update, I'll review over the weekend.

**Comment by webframp** [comment]
Fixed the travis annoyance by removing it, #120

**Review by webframp — APPROVED** [review]
Thanks @kovukono 

The Outfile and enterprise issue was also mentioned in #112 by @derekgroh 

I'll go ahead and pull this in now since it fixes things with the current resource and refactoring in #112 is still in a design in discussion

**Comment by webframp** [comment]
Not worried about the markdown lint failures, I'll fix those up on master.

**Pull request merged**
