### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by webframp**
Fixed resource ToC in README as well

----

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [X] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [X] Update README with any necessary configuration snippets

- [ ] Cookstyle (rubocop) passes

- [ ] Rspec (unit tests) passes

- [ ] Inspec (integration tests) passes

#### New Features

- [ ] Added a [Testing Artifact](https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts) as either an automated test or a manual artifact on the PR.

- [ ] Added documentation for it to the `README.md`

#### Known Compatibility Issues

### CODE REVIEW

**Comment by webframp** [comment]
@majormoses set as draft until we can have some ideas for #106 but otherwise ready.

**Comment by webframp** [comment]
Interesting failure with markdown link checker, but not concerned. Those links will exist once the release is tagged

**Comment by majormoses** [comment]
I wonder if we should consider this release independant of that issue, its not introduced by the changes being released. It's a poor user experience because of an upstream change, IMO we can tackle that independently.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by webframp** [comment]
> I wonder if we should consider this release independant of that issue, its not introduced by the changes being released. It's a poor user experience because of an upstream change, IMO we can tackle that independently.

Yea, I'm fine with that. Can you handle tagging and release to supermarket?

**Comment by majormoses** [comment]
Cheers:
- https://supermarket.chef.io/cookbooks/sensu-go/versions/1.3.0
- https://github.com/sensu/sensu-go-chef/releases/tag/1.3.0

**Pull request merged**
