### PR TITLE
add a debug option for `sensu_ctl` resource

### PR DESCRIPTION
**Pull request by majormoses**
This is useful for debugging but should be done with extreme caution as it could increase the likelihood of secrets being exposed where they need not be.

Signed-off-by: Ben Abrams <me@benabrams.it>

## Pull Request Checklist

https://sensucommunity.slack.com/archives/C9BB9AW7K/p1556243025188500

#### General

- [ ] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Cookstyle (rubocop) passes

- [ ] Foodcritic passes

- [ ] Rspec (unit tests) passes

- [ ] Inspec (integration tests) passes

#### Purpose
Allow users to toggle additional unsafe debug

#### Known Compatibility Issues
none

### CODE REVIEW

**Comment by webframp** [comment]
@majormoses just some minor lint stuff to fixup but then looks ok to merge to me.

**Comment by majormoses** [comment]
Im guessing we are not pinning our version of cookstyle, I can fix up those lints. I am not opposed (right now to leave it unpinned but eventually we will want to pin those).

**Comment by majormoses** [comment]
https://travis-ci.org/sensu/sensu-go-chef/jobs/530114249#L525 seems like its because of chefs recent changes to their licensing, I will have to dig into how we work with that. My understanding is that since this is an OSS cookbook we can add something to travis to accept the license but I need to dig what that is.

**Comment by webframp** [comment]
Yea, been dealing with this recently as well. Seems like chef still has some details to work out here. 

https://discourse.chef.io/t/cannot-accept-chef-client-license-on-bootstrapping/15120

In my case we are pinning to v14 for private use for now until licensing impact is clearer on v15. For an oss cookbook I’m not sure.

**Comment by majormoses** [comment]
ah its coming from test-kitchen not chef itself :angry: 

https://docs.chef.io/chef_license_accept.html#test-kitchen

I will take another crack at it this weekend.

**Pull request merged**
